accounts/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, UserRegisterView

app_name = 'accounts'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
]

course/urls.py
from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    CourseVideoView,
    CourseVideoListView
)

app_name = 'course'
urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    path('<int:course_id>/<str:course_slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('video/<int:video_id>/<str:video_slug>/', CourseVideoView.as_view(), name='video_course'),
    path(
        '<int:course_id>/<str:course_slug>/video/list/',
        CourseVideoListView.as_view(), name='course_video_list'
    )
]

home/urls.py
from django.urls import path
from .views import HomeView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

payment/urls.py
from django.urls import path
from .views import (
    CartView,

    CartAddCourseView,
    CartRemoveCourseView,

    OrderCreateView,
    OrderDetailView,

    SendRequestView,
    VerifyView
)

app_name = 'payment'
cart_urlpatterns = [
    path('cart/add/<int:course_id>/', CartAddCourseView.as_view(), name='cart_add_course'),
    path('cart/remove/<int:course_id>/', CartRemoveCourseView.as_view(), name='cart_remove_course'),
]
order_urlpatterns = [
    path('order/create/', OrderCreateView.as_view(), name='order_creation'),
    path('order/detail/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
]
zarinpal_urlpatterns = [
    path('request/<int:pk>/', SendRequestView.as_view(), name='request'),
    path('order/verify/', VerifyView.as_view(), name='verify'),
]

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart_detail'),
] + cart_urlpatterns + order_urlpatterns + zarinpal_urlpatterns

tutorialism/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # root path
    path('', include('home.urls', namespace='home')),
    path('', include('accounts.urls', namespace='accounts')),

    path('courses/', include('course.urls', namespace='course')),
    path('category/', include('category.urls', namespace='category')),
    path('video/', include('video.urls', namespace='video')),
    path('payment/', include('payment.urls', namespace='payment')),
    # ckeditor file path
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from .views import ShortVideoListView, ShortVideoDetailView

app_name = 'video'
urlpatterns = [
    path('short/', ShortVideoListView.as_view(), name='short_video_list'),
    path('short/<int:video_id>/<str:video_slug>/', ShortVideoDetailView.as_view(), name='short_video_detail'),
]

templates/includes/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

templates/includes/messages.html
{% load static %}

{% if messages %}
    <ul class="messages">
        {% for msg in messages %}
            <h5 class="alert alert-{{ msg.tags }}"
                style="text-align: center; margin-top: 3%; color: #323232;">
                {{ msg }}
            </h5>
        {% endfor %}
    </ul>
{% endif %}

templates/includes/navbar.html
<div class="header">
    <div class="logo">
        <a href="{% url 'home:home' %}" style="text-decoration: none; color: #FFFFFF;">توتوریالیسم</a>
    </div>
    <div class="menu">
        <!-- DROPDOWN -->
        <div class="dropdown">
            <button class="dropbtn">حساب کاربری</button>
            <div class="dropdown-content">
                {% if request.user.is_authenticated %}
                    <p class="link">
                        <div class="title text text-center">{{ request.user.username }}</div>
                        <div class="bar"></div>
                    </p>
                    <a href="{% url 'accounts:logout' %}" class="link">
                        <div class="title">خروج</div>
                        <div class="bar"></div>
                    </a>
                {% else %}
                    <a href="{% url 'accounts:login' %}" class="link">
                        <div class="title">ورود</div>
                        <div class="bar"></div>
                    </a>
                    <a href="{% url 'accounts:register' %}" class="link">
                        <div class="title">ثبت نام</div>
                        <div class="bar"></div>
                    </a>
                {% endif %}
            </div>
        </div>
        <a href="{% url 'course:course_list' %}" class="link">
            <div class="title">دوره ها</div>
            <div class="bar"></div>
        </a>
        <a href="{% url 'video:short_video_list' %}" class="link">
            <div class="title">ویدیو های کوتاه</div>
            <div class="bar"></div>
        </a>
        <a href="{% url 'payment:cart_detail' %}" class="link">
            <div class="title">سبد خرید</div>
            <div class="bar"></div>
        </a>
        <!-- END DROPDOWN -->
    </div>
</div>