course/urls.py
from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    CourseVideoView,
    CourseVideoListView
)

app_name = 'course'
urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    path('<int:course_id>/<str:course_slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('video/<int:video_id>/<str:video_slug>/', CourseVideoView.as_view(), name='video_course'),
    path(
        '<int:course_id>/<str:course_slug>/video/list/',
        CourseVideoListView.as_view(), name='course_video_list'
    )
]

home/urls.py
from django.urls import path
from .views import HomeView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

payment/urls.py
from django.urls import path
from .views import (
    CartView,

    CartAddCourseView,
    CartRemoveCourseView,

    OrderCreateView,
    OrderDetailView,

    SendRequestView,
    VerifyView
)

app_name = 'payment'
cart_urlpatterns = [
    path('cart/add/<int:course_id>/', CartAddCourseView.as_view(), name='cart_add_course'),
    path('cart/remove/<int:course_id>/', CartRemoveCourseView.as_view(), name='cart_remove_course'),
]
order_urlpatterns = [
    path('order/create/', OrderCreateView.as_view(), name='order_creation'),
    path('order/detail/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
]
zarinpal_urlpatterns = [
    path('request/<int:pk>/', SendRequestView.as_view(), name='request'),
    path('order/verify/', VerifyView.as_view(), name='verify'),
]

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart_detail'),
] + cart_urlpatterns + order_urlpatterns + zarinpal_urlpatterns

tutorialism/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # root path
    path('', include('home.urls', namespace='home')),
    path('', include('accounts.urls', namespace='accounts')),

    path('courses/', include('course.urls', namespace='course')),
    path('category/', include('category.urls', namespace='category')),
    path('video/', include('video.urls', namespace='video')),
    path('payment/', include('payment.urls', namespace='payment')),
    # ckeditor file path
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models/course.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from category.models import Category


class CourseCategory(Category):
    banner = models.ImageField(
        upload_to='images/category/course-banner/',
        null=True,
        blank=True,
        verbose_name=_("بنر")
    )

    class Meta:
        verbose_name = _("دسته بندی دوره ها")
        verbose_name_plural = _("دسته بندی های دوره ها")

    def get_absolute_url(self):
        return reverse(
            'category:course_category_detail',
            kwargs={'course_category_id': self.id, 'course_category_slug': self.slug}
        )

course/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField

from category.models import CourseCategory
from teacher.models import Teacher
from accounts.models import User
from common.models import BaseModel


class Course(BaseModel):
    title = models.CharField(
        max_length=50,
        verbose_name=_("عنوان دوره")
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name='courses',
        verbose_name=_("آموزگار")
    )
    section = models.CharField(
        max_length=3,
        verbose_name=_("تعداد قسمت ها")
    )
    description = RichTextUploadingField(verbose_name=_("توضیحات"))
    categories = models.ManyToManyField(
        CourseCategory,
        related_name='courses',
        verbose_name=_("دسته بندی ها")
    )
    price = models.PositiveIntegerField(
        default=0,
        help_text=_("به ریال وارد شود"),
        verbose_name=("قیمت")
    )
    discount = models.PositiveIntegerField(
        verbose_name=_("درصد تخفیف"),
        null=True,
        blank=True
    )
    banner = models.ImageField(
        upload_to='images/course-banner/',
        verbose_name=_("بنر")
    )
    slug = models.SlugField(
        unique=True,
        null=True,
        blank=True,
        allow_unicode=True,
        verbose_name=_("اسلاگ")
    )
    sold_to = models.ManyToManyField(
        User,
        related_name='courses',
        blank=True,
        verbose_name=_("خرید ها")
    )
    sale_count = models.PositiveIntegerField(
        default=0,
        verbose_name=_("تعداد فروش")
    )

    class Meta:
        verbose_name = _("دوره")
        verbose_name_plural = _("دوره ها")

    def __str__(self):
        return self.title

    @property
    def discount_price(self):
        price = self.price
        discount = self.discount
        discount_price = discount * price
        division_discount_price = discount_price / 100
        subtract_result = division_discount_price - price
        result = int(abs(subtract_result))
        return result
    
    def get_absolute_url(self):
        return reverse(
            'course:course_detail',
            kwargs={'course_id': self.id, 'course_slug': self.slug}
        )

video/models/course.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from video.models import Video
from course.models import Course


class CourseVideo(Video):
    video = models.FileField(
        upload_to='videos/courses/',
        verbose_name=_("ویدیو")
    )
    courses = models.ManyToManyField(
        Course,
        related_name='videos',
        verbose_name=_("دوره ها")
    )
    section = models.CharField(
        max_length=2,
        verbose_name=_("شماره قسمت")
    )
    is_free = models.BooleanField(default=False, verbose_name=_("رایگان"))
    banner = models.ImageField(
        upload_to='images/course-videos/',
        verbose_name=_("بنر")
    )

    class Meta:
        verbose_name = _("ویدیو دوره ها")
        verbose_name_plural = _("ویدیو های دوره ها")

    def get_absolute_url(self):
        return reverse(
            "course:video_course",
            kwargs={'video_id': self.id, 'video_slug': self.slug}
        )

course/views.py
from django.shortcuts import render
from django.views import View
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin

from urllib.parse import unquote

from .models import Course
from video.models import CourseVideo


class CourseListView(View):
    def get(self, request):
        courses = Course.objects.all()
        courses_length = len(courses)
        # paginator
        page = request.GET.get('page', 1)
        paginator = Paginator(courses, 8)
        try:
            course_list = paginator.page(page)
        except PageNotAnInteger:
            course_list = paginator.page(1)
        except EmptyPage:
            course_list = paginator.page(paginator.num_pages)

        context = {
            'courses': course_list,
            'courses_length': courses_length
        }
        return render(request, 'course/course_list.html', context)


class CourseDetailView(View):
    def get(self, request, course_id=None, course_slug=None):
        course_slug = unquote(course_slug)
        course = Course.objects.prefetch_related('videos').filter(id=course_id, slug=unquote(course_slug)).first()
        introducing_video = course.videos.first()
        videos = CourseVideo.objects.filter(courses=course)[1:]

        context = {
            'introducing_video': introducing_video,
            'course': course,
            'videos': videos
        }
        return render(request, 'course/course_detail.html', context)


class CourseVideoListView(View):
    def get(self, request, course_id=None, course_slug=None):
        videos = CourseVideo.objects.filter(
            Q(courses__id=course_id) &
            Q(courses__slug=course_slug)
        )
        context = {'videos': videos}
        return render(request, 'course/course_video_list.html', context)


class CourseVideoView(LoginRequiredMixin, View):
    def get(self, request, video_id=None, video_slug=None):
        video = CourseVideo.objects.prefetch_related('courses').filter(id=video_id, slug=video_slug).first()
        # video = get_object_or_404(CourseVideo, id=video_id, slug=video_slug)
        course_paid = video.courses.filter(sold_to=request.user).iterator()

        context = {
            'video': video,
            'course_paid': course_paid
        }
        return render(request, 'course/video_course.html', context)

course/templates/course/course_detail.html
{% extends 'base.html' %}

{% block title %} دوره {{ course.title }} {% endblock title %}

{% block content %}

    <div class="detail">
        <!-- BREADCRUMB -->
        <nav aria-label="breadcrumb" dir="ltr">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
              <li class="breadcrumb-item"><a href="{% url 'course:course_list' %}">دوره ها</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ course.title }}</li>
            </ol>
        </nav>
        <!-- END BREADCRUMB -->

        <img src="{{ course.banner.url }}" class="img-fluid detail-img" alt="{{ course.title }}">
        <p class="lead detail-lead">
            {{ course.title }}
        </p>
        <hr style="width: 50%; margin: auto;">
        <p class="detail-description">{{ course.description|safe }}</p>
        <hr style="width: 50%; margin: auto;">
        <form action="{% url 'payment:cart_add_course' course.id %}" method="post">
			{% csrf_token %}
			<div class="d-grid gap-2 col-4 mx-auto mt-2" style="text-align: center; margin: auto;">
                <input class="btn btn-primary videos-btn" type="submit" value="افزودن به سبد خرید">
            </div>
		</form>

        <hr style="width: 50%; margin: auto; margin-top: 1%;">
        <div class="d-grid gap-2 col-6 mx-auto mt-2">
            <a href="{% url 'course:course_video_list' course.id course.slug %}" 
                class="btn btn-primary videos-btn" type="button" target="_blank"
            >
                ویدیو های دوره
            </a>
        </div>     
    </div>

{% endblock content %}

course/templates/course/course_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} لیست دوره ها {% endblock title %}

{% block content %}

    <div class="row">
        {% for course in courses %}
        <div class="col-sm-3 col-lg-3">
            <div class="card" style="height: 100%; width: 90%;">
                <!-- <img src="{{ course.banner.url }}" class="card-img-top" alt="..." height="90%" width="90%"> -->
                <div class="card-body">
                    <h5 class="card-title text-center">{{ course.title }}</h5>
                    <p class="card-text card-detail">{{ course.teacher }}</p>
                    {% if course.price == 0 %}
                        <p class="card-text card-detail">رایگان</p>
                    {% else %}
                        {% if course.discount %}
                            <p class="card-text card-detail">{{ course.dicount_price|intcomma:False }}</p>
                        {% else %}
                            <p class="card-text card-detail">{{ course.price|intcomma:False }}</p>
                        {% endif %}
                    {% endif %}
                    <a href="{{ course.get_absolute_url }}" class="btn btn-primary btn-detail">جزئیات بیشتر</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

course/templates/course/course_video_list.html
{% extends 'base.html' %}

{% block title %} لیست ویدیو های دوره {% endblock title %}

{% block content %}

    <div class="row">
        {% for video in videos %}
        <div class="col-sm-3 col-lg-3">
            <div class="card" style="height: 100%; width: 90%;">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ video.title }}</h5>
                    <p class="card-text card-detail">{{ video.teacher }}</p>
                    <p class="card-text card-detail">قسمت {{ video.section }}</p>
                    <a href="{{ video.get_absolute_url }}" class="btn btn-primary btn-detail">تماشا ویدیو</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

course/templates/course/video_course.html
{% extends 'base_video_detail.html' %}

{% block title %} {{ video.title }} {% endblock title %}

{% block content %}
    <div class="detail">
        <div class="jumbotron">
            <h3 style="text-align: center; margin-top: 2%;">
                <a href="{% url 'home:home' %}" class="btn btn-primary videos-btn">بازگشت به صفحه اصلی سایت</a>
            </h3>
            <!-- BREADCRUMB -->
            <nav aria-label="breadcrumb" dir="ltr">
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
                <li class="breadcrumb-item"><a href="{% url 'course:course_list' %}">دوره ها</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ video.title }}</li>
                </ol>
            </nav>
            <!-- END BREADCRUMB -->
        </div>
        {% if course_paid %}
            <video controls width="70%" style="margin-left: 15%; margin-top: 5%;">
                <source src="{{ video.video.url }}" />
            </video>
        {% endif %}
    </div>
{% endblock content %}