course/urls.py
from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    CourseVideoView,
    CourseVideoListView
)

app_name = 'course'
urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    path('<int:course_id>/<str:course_slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('video/<int:video_id>/<str:video_slug>/', CourseVideoView.as_view(), name='video_course'),
    path(
        '<int:course_id>/<str:course_slug>/video/list/',
        CourseVideoListView.as_view(), name='course_video_list'
    )
]

home/urls.py
from django.urls import path
from .views import HomeView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

payment/urls.py
from django.urls import path
from .views import (
    CartView,

    CartAddCourseView,
    CartRemoveCourseView,

    OrderCreateView,
    OrderDetailView,

    SendRequestView,
    VerifyView
)

app_name = 'payment'
cart_urlpatterns = [
    path('cart/add/<int:course_id>/', CartAddCourseView.as_view(), name='cart_add_course'),
    path('cart/remove/<int:course_id>/', CartRemoveCourseView.as_view(), name='cart_remove_course'),
]
order_urlpatterns = [
    path('order/create/', OrderCreateView.as_view(), name='order_creation'),
    path('order/detail/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
]
zarinpal_urlpatterns = [
    path('request/<int:pk>/', SendRequestView.as_view(), name='request'),
    path('order/verify/', VerifyView.as_view(), name='verify'),
]

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart_detail'),
] + cart_urlpatterns + order_urlpatterns + zarinpal_urlpatterns

tutorialism/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # root path
    path('', include('home.urls', namespace='home')),
    path('', include('accounts.urls', namespace='accounts')),

    path('courses/', include('course.urls', namespace='course')),
    path('category/', include('category.urls', namespace='category')),
    path('video/', include('video.urls', namespace='video')),
    path('payment/', include('payment.urls', namespace='payment')),
    # ckeditor file path
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from course.models import Course
from accounts.models import User
from common.models import BaseModel


class Order(BaseModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="orders",
        verbose_name=_("کاربر")
    )
    total_price = models.PositiveIntegerField(
        default=0,
        verbose_name=_("قیمت کل")
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name=_("وضعیت پرداخت")
    )

    class Meta:
        verbose_name = _("سفارش")
        verbose_name_plural = _("سفارش ها")

    def __str__(self):
        return str(self.user.phone)


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name=_("سفارش")
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="order_items",
        verbose_name=_("دوره")
    )
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name=_("تعداد")
    )
    price = models.PositiveIntegerField(
        default=0,
        verbose_name=_("قیمت")
    )

    class Meta:
        verbose_name = _("آیتم سفارش ها")
        verbose_name_plural = _("آیتم های سفارش")

    def __str__(self):
        return str(self.course.title)

payment/views/cart_course.py
from django.shortcuts import redirect
from django.views import View

from urllib.parse import unquote

from payment.cart import Cart
from course.models import Course

CART_DETAIL_URL = 'payment:cart_detail'


class CartAddCourseView(View):
    def post(self, request, course_id=None):
        cart = Cart(request)
        course = Course.objects.filter(id=course_id).first()
        cart.add(course)
        return redirect(CART_DETAIL_URL)


class CartRemoveCourseView(View):
    def get(self, request, course_id=None):
        cart = Cart(request)
        course = Course.objects.filter(id=course_id).first()
        cart.remove(course)
        return redirect(CART_DETAIL_URL)

payment/views/cart_detail.py
from django.shortcuts import render
from django.views import View

from payment.cart import Cart


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        cart_length = len([item for item in cart])    # length of cart values
        context = {
            'cart': cart,
            'cart_length': cart_length
        }
        return render(request, 'payment/cart_detail.html', context)

payment/views/order.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from payment.cart import Cart
from payment.models import Order, OrderItem


class OrderDetailView(LoginRequiredMixin, View):
    def get(self, request, order_id=None):
        order = get_object_or_404(Order, id=order_id)
        context = {'order': order}
        return render(request, 'payment/order_detail.html', context)


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(
            user=request.user,
            total_price=cart.total_price()
        )
        for item in cart:
            OrderItem.objects.bulk_create(
                [
                    OrderItem(
                        order=order,
                        course=item['course'],
                        price=item['price'],
                        quantity=item['quantity']
                    )
                ],
                ignore_conflicts=True,
            )
        cart.clear()
        return redirect('payment:order_detail', order.id)

payment/views/zarinpal.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse

import requests
import json

from payment.models import Order, OrderItem

MERCHANT = "your-merchant-id"
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
# Important: need to edit for realy server.
CallbackURL = "http://127.0.0.1:8000/payment/order/verify/"


class SendRequestView(View):
    def post(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        request.session['order_id'] = str(order.id)
        req_data = {
            "merchant_id": MERCHANT,
            "amount": order.total_price,
            "callback_url": CallbackURL,
            "description": description,
            "metadata": {"mobile": str(request.user.phone), "email": str(request.user.email)}
        }
        req_header = {
            "accept": "application/json",
            "content-type": "application/json"
        }
        req = requests.post(
            url=ZP_API_REQUEST,
            data=json.dumps(req_data),
            headers=req_header
        )
        authority = req.json()['data']['authority']
        if len(req.json()['errors']) == 0:
            return redirect(ZP_API_STARTPAY.format(authority=authority))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


class VerifyView(View):
    def get(self, request):
        t_status = request.GET.get('Status')
        t_authority = request.GET['Authority']
        order_id = request.session['order_id']
        order = Order.objects.get(id=int(order_id))
        order_items = OrderItem.objects.get(order=order)
        courses = order_items.course

        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json",
                          "content-type": "application/json'"}
            req_data = {
                "merchant_id": MERCHANT,
                "amount": order.total_price,
                "authority": t_authority
            }
            req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
            if len(req.json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    order.is_paid = True
                    order.save()
                    courses.sold_to.add(order.user)
                    courses.sale_count+=1
                    courses.save()
                    return render(request, 'payment/verify_success.html')
                elif t_status == 101:
                    return HttpResponse('Transaction submitted : ' + str(
                        req.json()['data']['message']
                    ))
                else:
                    return HttpResponse('Transaction failed.\nStatus: ' + str(
                        req.json()['data']['message']
                    ))
            else:
                e_code = req.json()['errors']['code']
                e_message = req.json()['errors']['message']
                return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
        else:
            return redirect('home:home')
    

payment/templates/payment/cart_detail.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} سبد خرید {% endblock title %}

{% block content %}

    {% if cart != None %}
        <div class="row">
            <div class="col-lg-5">
                <br>
                <div class="box-element">
                    <div class="cart-row">
                        <div style="flex:2"><strong>نام</strong></div>
                        <div style="flex:2"><strong>قیمت</strong></div>
                        <div style="flex:1"><strong>حذف</strong></div>

                    </div>
                    {% for value in cart %}
                    <div class="cart-row">
                        <div style="flex:2"><p>{{ value.course.title }}</p></div>
                        <div style="flex:2"><p>{{ value.price|intcomma:False}} ریال </p></div>
                        <div style="flex:1">
                            <a class="btn btn-sm btn-danger"
                                href="{% url 'payment:cart_remove_course' value.course_id %}">
                                حذف
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-7">
                <div class="box-element">

                    <a  class="btn btn-outline-continue-shpping" href="{% url 'course:course_list' %}">&#x2190; ادامه خرید</a>

                    <br>
                    <br>
                    <table class="table" style="margin: auto;">
                        <tr>
                            <th><h5>تعداد: <strong>{{ cart_length }}</strong></h5></th>
                            <th><h5>جمع سبد خرید:<strong>{{ cart.total_price|intcomma:False }}</strong></h5></th>
                            <th>
                                <div class="d-grid gap-2 col-7 mx-auto mt-2">
                                    <a href="{% url 'payment:order_creation' %}" style="float:right; margin:5px;"
                                        class="btn btn-primary videos-btn" type="button" target="_blank"
                                    >
                                        تصویه حساب
                                    </a>
                                </div>
                            </th>
                        </tr>
                    </table>

                </div>
            </div>
        </div>
    {% else %}
        <h1 style="text-align:center;padding: 100px">سبد خرید شما خالی است</h1>
    {% endif %}

{% endblock content %}

payment/templates/payment/order_detail.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}تسویه حساب{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-lg-5">
            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"><strong>نام</strong></div>
                    <div style="flex:2"><strong>قیمت</strong></div>

                </div>
                {% for value in order.items.all %}
                <div class="cart-row">
                    <div style="flex:2"><p>{{ value.course.title }}</p></div>
                    <div style="flex:2"><p>{{ value.price|intcomma:False}} ریال </p></div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-7">
            <div class="box-element">
                <br>
                <table class="table" style="margin: auto;">
                    <tr>
                        <th><h5>جمع سبد خرید: <strong>{{ order.total_price|intcomma:False }}</strong></h5></th>
                        <th>
                            <form action="{% url 'payment:request' order.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-bank">
                                    اقدام به پرداخت
                                </button>
                            </form>
                        </th>
                    </tr>
                </table>
                <br>
            </div>
        </div>
    </div>

{% endblock content %}

payment/templates/payment/verify_success.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <main>

        <section class="container py-5">
            <h3 class="my-3 font-weight-bold" style="color: #00c054">پرداخت شما با موفقیت انجام شد</h3>
            <a href="{% url 'home:home' %}" class="btn btn-success">بازگشت به صفحه اصلی</a>
        </section>

    </main>

{% endblock %}